import type { Handler } from '@netlify/functions';
import { getStore } from '@netlify/blobs';

// Netlify normally injects the Blobs context automatically. The explicit
// fallback keeps the store available on sites where Blobs has not yet been
// provisioned in the UI, using the site-scoped credentials configured in the
// site's runtime environment.
const store = getStore({
  name: 'signal-arc-production',
  consistency: 'strong',
  siteID: process.env.NETLIFY_SITE_ID,
  token: process.env.NETLIFY_BLOBS_TOKEN,
});
const cookieName = 'signal_session';
const headers = { 'content-type': 'application/json', 'cache-control': 'no-store' };
type Job = { id: string; slug: string; company: string; role: string; location: string; kind: string; salary: string; description: string; tags: string[]; accent: string };
type Profile = { session_id: string; resume_text: string; full_name: string; headline: string; skills: string[] };
type Analysis = { session_id: string; job_id: string; score: number; reasons: string[]; updated_at: string };
type Draft = { id: string; session_id: string; job_id: string; body: string; status: string; created_at: string; updated_at: string };
type State = { profiles: Record<string, Profile>; analysis: Analysis[]; drafts: Draft[]; usage: { session_id: string; event: string; units: number; created_at: string }[]; jobs: Job[] };
const seedJobs: Job[] = [
  { id:'lattice-frontend', slug:'lattice-frontend', company:'Lattice Systems', role:'Senior Frontend Engineer', location:'Remote · EU / India', kind:'Full-time', salary:'$145k — $180k', description:'Own the interface layer for a developer platform used by teams shipping critical infrastructure. Shape a component system, partner with product, and turn complex state into calm experiences.', tags:['react','typescript','design systems','systems'], accent:'#d5ff55' },
  { id:'northstar-product', slug:'northstar-product', company:'Northstar Labs', role:'Product Engineer', location:'Bengaluru · Hybrid', kind:'Full-time', salary:'₹36L — ₹52L', description:'Build fast experiments from customer insight to production. The team values product sense, clear writing, and engineers who can move between interface, data, and APIs.', tags:['react','product','api','python'], accent:'#ff8d66' },
  { id:'atlas-ai', slug:'atlas-ai', company:'Atlas AI', role:'AI Platform Engineer', location:'New York · Remote', kind:'Full-time', salary:'$155k — $210k', description:'Design reliable evaluation and observability loops for AI products. Make model behavior legible through structured data, instrumentation, and thoughtful tooling.', tags:['python','llm','postgres','observability'], accent:'#9b8cff' },
  { id:'morrow-studio', slug:'morrow-studio', company:'Morrow Studio', role:'Creative Technologist', location:'London · Hybrid', kind:'Contract', salary:'£500 — £700 / day', description:'Create expressive digital tools and prototypes that feel as good as they function. Strong visual taste and a willingness to work across code, motion, and narrative are essential.', tags:['three.js','motion','react','prototyping'], accent:'#65d8ff' },
];
const emptyState = (): State => ({ profiles:{}, analysis:[], drafts:[], usage:[], jobs:seedJobs });
async function load(): Promise<State> { return ((await store.get('state.json', { type:'json' })) as State | null) || emptyState(); }
async function save(state: State) { await store.setJSON('state.json', state); }
function json(body: unknown, status = 200, extra: Record<string,string> = {}) { return { statusCode: status, headers: { ...headers, ...extra }, body: JSON.stringify(body) }; }
function sessionFrom(event: Parameters<Handler>[0]) { return event.headers.cookie?.match(new RegExp(`${cookieName}=([^;]+)`))?.[1] || ''; }
function parseResume(text: string) { const normalized=text.replace(/\s+/g,' ').trim(); const all=['react','typescript','javascript','python','postgres','llm','three.js','design systems','product','api','motion','observability','node']; const skills=all.filter((s) => normalized.toLowerCase().includes(s)); const lines=text.split(/\n+/).map((x) => x.trim()).filter(Boolean); return { full_name: lines[0]?.slice(0,70) || 'Your name', headline: lines[1]?.slice(0,100) || 'Product-minded builder', skills }; }
function analyze(profile: Profile, job: Job) { const hits=job.tags.filter((tag) => profile.skills.includes(tag)); const score=Math.min(96,Math.max(42,48+hits.length*11+(profile.skills.includes('product')&&job.tags.includes('product')?9:0))); const reasons=hits.length?hits.map((hit) => `Your profile signals ${hit}.`):['Your systems thinking can transfer here.','The role has room for a strong product narrative.']; return { score, reasons }; }
function draft(profile: Profile, job: Job) { const skills=profile.skills.slice(0,4).join(', '); return `Hi ${job.company} team,\n\nI’m ${profile.full_name}, a ${profile.headline || 'product-minded builder'} who enjoys turning complex systems into clear, useful experiences. The ${job.role} role stood out because it sits at the intersection of ${skills || 'product craft and engineering'}.\n\nIn my recent work I’ve built end-to-end products, shaped reliable APIs, and cared deeply about the final interaction—not just the implementation. I’d love to bring that same mix of systems thinking and visual clarity to ${job.company}.\n\nI’d be glad to share a focused walkthrough of the work most relevant to this team.\n\nBest,\n${profile.full_name}`; }
export const handler: Handler = async (event) => { try {
  const path=event.path.replace(/^.*?\.netlify\/functions\/api\/?/,'').replace(/^api\//,''); const body=event.body?JSON.parse(event.body):{}; const existing=sessionFrom(event); const sessionId=existing||crypto.randomUUID(); const cookie=existing?'':`${cookieName}=${sessionId}; Path=/; Max-Age=31536000; SameSite=Lax; Secure`; const state=await load();
  if (event.httpMethod==='GET' && (path==='' || path==='health')) return json({status:'ok',service:'signal-arc',database:'netlify-blobs'},200,cookie?{'set-cookie':cookie}:{});
  if (event.httpMethod==='GET' && path==='bootstrap') return json({profile:state.profiles[sessionId]||null,jobs:state.jobs,analysis:state.analysis.filter((x)=>x.session_id===sessionId),drafts:state.drafts.filter((x)=>x.session_id===sessionId).sort((a,b)=>b.created_at.localeCompare(a.created_at)),usageCount:state.usage.filter((x)=>x.session_id===sessionId).reduce((n,x)=>n+x.units,0)},200,cookie?{'set-cookie':cookie}:{});
  if (event.httpMethod==='POST' && path==='profile') { const parsed=parseResume(String(body.resumeText||'')); const profile={session_id:sessionId,resume_text:String(body.resumeText||''),...parsed}; state.profiles[sessionId]=profile; state.usage.push({session_id:sessionId,event:'resume.parse',units:1,created_at:new Date().toISOString()}); await save(state); return json({profile},200,cookie?{'set-cookie':cookie}:{}); }
  if (event.httpMethod==='POST' && path==='analyze') { const profile=state.profiles[sessionId]; if(!profile)return json({error:'Add your resume signal first.'},400); const results=state.jobs.map((job)=>{const result=analyze(profile,job); const item={session_id:sessionId,job_id:job.id,...result,updated_at:new Date().toISOString()}; state.analysis=state.analysis.filter((x)=>!(x.session_id===sessionId&&x.job_id===job.id)); state.analysis.push(item); return {job_id:job.id,score:result.score,reasons:result.reasons};}); state.usage.push({session_id:sessionId,event:'jobs.analyze',units:state.jobs.length,created_at:new Date().toISOString()}); await save(state); return json({analysis:results}); }
  if (event.httpMethod==='POST' && path==='drafts') { const profile=state.profiles[sessionId]; const job=state.jobs.find((item)=>item.id===body.jobId); if(!profile||!job)return json({error:'Choose a role and add your profile first.'},400); const now=new Date().toISOString(); const item={id:crypto.randomUUID(),session_id:sessionId,job_id:job.id,body:draft(profile,job),status:'review',created_at:now,updated_at:now}; state.drafts.unshift(item); state.usage.push({session_id:sessionId,event:'draft.create',units:1,created_at:now}); await save(state); return json({draft:item}); }
  if (event.httpMethod==='POST' && path==='ingest') { if(!body.company||!body.role||!body.description)return json({error:'company, role, and description are required.'},400); const job={id:crypto.randomUUID(),slug:`custom-${crypto.randomUUID()}`,company:body.company,role:body.role,location:body.location||'Remote',kind:body.kind||'Full-time',salary:body.salary||'Not listed',description:body.description,tags:body.tags||[],accent:body.accent||'#d5ff55'}; state.jobs.push(job); await save(state); return json({job}); }
  return json({error:'Route not found.'},404);
 } catch (error) { return json({error:error instanceof Error?error.message:'Unexpected error.'},500); } };
