import type { Handler } from '@netlify/functions';
const headers = { 'content-type': 'application/json', 'cache-control': 'no-store' };
const url = process.env.SUPABASE_URL ?? '';
const key = process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';
const cookieName = 'signal_session';
type Row = Record<string, any>;
function supabase(path: string, init: RequestInit = {}) { return fetch(`${url}/rest/v1/${path}`, { ...init, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(init.headers || {}) } }); }
function json(body: unknown, status = 200, extra: Record<string,string> = {}) { return { statusCode: status, headers: { ...headers, ...extra }, body: JSON.stringify(body) }; }
function parseCookie(event: Parameters<Handler>[0]) { return event.headers.cookie?.match(new RegExp(`${cookieName}=([^;]+)`))?.[1] ?? ''; }
async function ensureSession(event: Parameters<Handler>[0]) {
  const existing = parseCookie(event);
  if (existing) { await supabase(`signal_sessions?id=eq.${encodeURIComponent(existing)}`, { method:'PATCH', body: JSON.stringify({ last_seen: new Date().toISOString() }) }); return { id: existing, cookie: '' }; }
  const id = crypto.randomUUID();
  await supabase('signal_sessions', { method:'POST', headers:{ Prefer:'return=minimal' }, body: JSON.stringify({ id }) });
  return { id, cookie: `${cookieName}=${id}; Path=/; Max-Age=31536000; SameSite=Lax; Secure` };
}
async function rows(path: string) { const r = await supabase(path); if (!r.ok) throw new Error('Database request failed'); return await r.json() as Row[]; }
async function write(path:string, body:unknown, method='POST', prefer='return=representation') { const r=await supabase(path,{method,headers:{Prefer:prefer},body:JSON.stringify(body)}); if(!r.ok) throw new Error('Database write failed'); return await r.json().catch(()=>[]); }
function parseResume(text: string) { const normalized=text.replace(/\s+/g,' ').trim(); const all=['react','typescript','javascript','python','postgres','llm','three.js','design systems','product','api','motion','observability','node']; const skills=all.filter(s=>normalized.toLowerCase().includes(s)); const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean); return { full_name: lines[0]?.slice(0,70) || 'Your name', headline: lines[1]?.slice(0,100) || 'Product-minded builder', skills }; }
function analyze(profile: Row, job: Row) { const skills=(profile.skills||[]) as string[]; const tags=(job.tags||[]) as string[]; const hits=tags.filter((t:string)=>skills.includes(t)); const score=Math.min(96, Math.max(42, 48 + hits.length*11 + (skills.includes('product') && tags.includes('product') ? 9 : 0))); const reasons=hits.length ? hits.map((hit:string)=>`Your profile signals ${hit}.`) : ['Your systems thinking can transfer here.','The role has room for a strong product narrative.']; return { score, reasons }; }
function draft(profile: Row, job: Row) { const name=profile.full_name || 'there'; const skills=(profile.skills||[]).slice(0,4).join(', '); return `Hi ${job.company} team,\n\nI’m ${name}, a ${profile.headline || 'product-minded builder'} who enjoys turning complex systems into clear, useful experiences. The ${job.role} role stood out because it sits at the intersection of ${skills || 'product craft and engineering'}.\n\nIn my recent work I’ve built end-to-end products, shaped reliable APIs, and cared deeply about the final interaction—not just the implementation. I’d love to bring that same mix of systems thinking and visual clarity to ${job.company}.\n\nI’d be glad to share a focused walkthrough of the work most relevant to this team.\n\nBest,\n${name}`; }
export const handler: Handler = async (event) => { try {
  if (!url || !key) return json({ error:'Database is not configured.' }, 503);
  const session = await ensureSession(event); const path=event.path.replace(/^.*?\.netlify\/functions\/api\/?/, '').replace(/^api\//,''); const body=event.body?JSON.parse(event.body):{};
  if (event.httpMethod==='GET' && (path==='' || path==='health')) return json({ status:'ok', service:'signal-arc', database:'supabase-postgres' },200,session.cookie?{'set-cookie':session.cookie}:{});
  if (event.httpMethod==='GET' && path==='bootstrap') { const [profiles,jobs,analysis,drafts,usage]=await Promise.all([rows(`signal_profiles?session_id=eq.${session.id}&limit=1`),rows('signal_jobs?order=created_at.asc'),rows(`signal_analysis?session_id=eq.${session.id}`),rows(`signal_drafts?session_id=eq.${session.id}&order=created_at.desc`),rows(`signal_usage?session_id=eq.${session.id}`)]); return json({ profile:profiles[0]||null,jobs,analysis,drafts,usageCount:usage.reduce((n,r)=>n+Number(r.units||1),0) },200,session.cookie?{'set-cookie':session.cookie}:{}); }
  if (event.httpMethod==='POST' && path==='profile') { const parsed=parseResume(String(body.resumeText||'')); const profile={session_id:session.id,resume_text:String(body.resumeText||''),...parsed,updated_at:new Date().toISOString()}; await write('signal_profiles',profile,'POST','resolution=merge-duplicates,return=representation'); await write('signal_usage',{session_id:session.id,event:'resume.parse',units:1},'POST','return=minimal'); return json({profile}); }
  if (event.httpMethod==='POST' && path==='analyze') { const [p,jobs]=await Promise.all([rows(`signal_profiles?session_id=eq.${session.id}&limit=1`),rows('signal_jobs?order=created_at.asc')]); if(!p[0]) return json({error:'Add your resume signal first.'},400); const results=[]; for(const job of jobs){const result=analyze(p[0],job); await write('signal_analysis',{session_id:session.id,job_id:job.id,...result,updated_at:new Date().toISOString()},'POST','resolution=merge-duplicates,return=minimal'); results.push({job_id:job.id,...result});} await write('signal_usage',{session_id:session.id,event:'jobs.analyze',units:jobs.length},'POST','return=minimal'); return json({analysis:results}); }
  if (event.httpMethod==='POST' && path==='drafts') { const [p,j]=await Promise.all([rows(`signal_profiles?session_id=eq.${session.id}&limit=1`),rows(`signal_jobs?id=eq.${body.jobId}&limit=1`)]); if(!p[0]||!j[0]) return json({error:'Choose a role and add your profile first.'},400); const created=await write('signal_drafts',{session_id:session.id,job_id:j[0].id,body:draft(p[0],j[0]),status:'review'}); await write('signal_usage',{session_id:session.id,event:'draft.create',units:1},'POST','return=minimal'); return json({draft:created[0]}); }
  if (event.httpMethod==='POST' && path==='ingest') { const item=body; if(!item.company||!item.role||!item.description) return json({error:'company, role, and description are required.'},400); const created=await write('signal_jobs',{slug:`custom-${crypto.randomUUID()}`,company:item.company,role:item.role,location:item.location||'Remote',kind:item.kind||'Full-time',salary:item.salary||'Not listed',description:item.description,tags:item.tags||[],accent:item.accent||'#d5ff55'}); return json({job:created[0]}); }
  return json({error:'Route not found.'},404);
 } catch (error) { return json({error:error instanceof Error?error.message:'Unexpected error.'},500); } };
