import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, BarChart3, Check, ChevronRight, Code2, FileText, Gauge, Github, Layers3, LoaderCircle, Radar, Sparkles, Upload, X } from 'lucide-react';
import { OrbitScene } from './OrbitScene';

type Job = { id: string; company: string; role: string; location: string; kind: string; salary: string; description: string; tags: string[]; accent: string };
type Profile = { session_id: string; resume_text: string; full_name: string; headline: string; skills: string[] };
type Analysis = { job_id: string; score: number; reasons: string[] };
type Draft = { id: string; job_id: string; body: string; status: string };
const sample = `Yash Anand\nProduct engineer & creative technologist\n\nI build full-stack products with React, TypeScript, Node, Python, Postgres, and Three.js. I care about design systems, API reliability, motion, observability, and turning complex workflows into clear experiences.\n\nSelected work: open-source workflow automation engine, AI review tooling, interactive 3D product sites.`;
const demoJobs: Job[] = [
  { id:'demo-lattice', company:'Lattice Systems', role:'Senior Frontend Engineer', location:'Remote · EU / India', kind:'Full-time', salary:'$145k — $180k', description:'Own the interface layer for a developer platform used by teams shipping critical infrastructure.', tags:['react','typescript','design systems'], accent:'#d5ff55' },
  { id:'demo-northstar', company:'Northstar Labs', role:'Product Engineer', location:'Bengaluru · Hybrid', kind:'Full-time', salary:'₹36L — ₹52L', description:'Build fast experiments from customer insight to production across interface, data, and APIs.', tags:['react','product','api'], accent:'#ff8d66' },
  { id:'demo-atlas', company:'Atlas AI', role:'AI Platform Engineer', location:'New York · Remote', kind:'Full-time', salary:'$155k — $210k', description:'Design reliable evaluation and observability loops for AI products.', tags:['python','llm','postgres'], accent:'#9b8cff' },
  { id:'demo-morrow', company:'Morrow Studio', role:'Creative Technologist', location:'London · Hybrid', kind:'Contract', salary:'£500 — £700 / day', description:'Create expressive digital tools and prototypes that feel as good as they function.', tags:['three.js','motion','react'], accent:'#65d8ff' },
];
async function api(path: string, init?: RequestInit) { const r = await fetch(`/api/${path}`, { headers: { 'content-type': 'application/json' }, ...init }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Something went wrong.'); return data; }

export default function App() {
  const [profile, setProfile] = useState<Profile | null>(null); const [resumeText, setResumeText] = useState(''); const [jobs, setJobs] = useState<Job[]>([]); const [analysis, setAnalysis] = useState<Analysis[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [usage, setUsage] = useState(0); const [view, setView] = useState<'overview'|'signal'|'desk'|'api'>('overview'); const [selected, setSelected] = useState<Job | null>(null); const [busy, setBusy] = useState(''); const [toast, setToast] = useState('');
  useEffect(() => { api('bootstrap').then((d) => { setProfile(d.profile); setResumeText(d.profile?.resume_text || ''); setJobs(d.jobs); setAnalysis(d.analysis); setDrafts(d.drafts); setUsage(d.usageCount || 0); }).catch(() => { setJobs(demoJobs); }); }, []);
  const scoreFor = (id: string) => analysis.find((item) => item.job_id === id);
  const sortedJobs = useMemo(() => [...jobs].sort((a,b) => (scoreFor(b.id)?.score || 0) - (scoreFor(a.id)?.score || 0)), [jobs, analysis]);
  async function saveProfile() { setBusy('profile'); try { const d = await api('profile', { method:'POST', body: JSON.stringify({ resumeText }) }); setProfile(d.profile); setUsage((x) => x + 1); setToast('Profile signal updated.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function analyzeJobs() { setBusy('analyze'); try { const d = await api('analyze', { method:'POST', body:'{}' }); setAnalysis(d.analysis); setUsage((x) => x + jobs.length); setToast('Fit map recalculated across the role orbit.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function createDraft(job: Job) { setBusy(`draft-${job.id}`); try { const d = await api('drafts', { method:'POST', body: JSON.stringify({ jobId: job.id }) }); setDrafts((old) => [d.draft, ...old]); setSelected(job); setView('desk'); setUsage((x) => x + 1); setToast('Draft ready for your review.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  return <div className="app-shell">
    <header className="topbar"><a href="#top" className="wordmark"><span className="mark">◎</span> signal<span className="slash">/</span>arc</a><nav><button onClick={() => setView('overview')} className={view==='overview'?'active':''}>Workspace</button><button onClick={() => setView('signal')} className={view==='signal'?'active':''}>Resume signal</button><button onClick={() => setView('api')} className={view==='api'?'active':''}>API studio</button></nav><a className="github" href="https://github.com/YashAnand69" target="_blank" rel="noreferrer"><Github size={16}/> Build log <ArrowUpRight size={14}/></a></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> CAREER INTELLIGENCE / 01</div><h1>Make your next move <i>legible.</i></h1><p className="lede">Signal Arc turns a resume, a role, and a little intent into a sharper application. See the fit. Keep the human voice.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById('workspace')?.scrollIntoView({ behavior:'smooth' })}>Open the workspace <ChevronRight size={18}/></button><span className="micro">Human review stays in the loop.</span></div></div><div className="hero-visual"><OrbitScene/><div className="orbit-caption"><span>ORBIT / 04</span><strong>Potential<br/>in motion</strong></div></div><div className="hero-index">A — 01<br/>B — 04<br/>C — ∞</div></section>
      <section className="ticker"><span>PARSE</span><b>→</b><span>COMPARE</span><b>→</b><span>EXPLAIN</span><b>→</b><span>REVIEW</span><b>→</b><span>APPLY WITH INTENT</span></section>
      <section id="workspace" className="workspace"><aside className="sidebar"><div className="side-top"><span className="eyebrow">YOUR SIGNAL / 01</span><span className="live-dot">LIVE</span></div><h2>One clear<br/><i>next step.</i></h2><p>Build a small, honest system for the work you want.</p><div className="side-nav"><button onClick={() => setView('overview')} className={view==='overview'?'selected':''}><Radar size={17}/> Fit map <span>01</span></button><button onClick={() => setView('signal')} className={view==='signal'?'selected':''}><FileText size={17}/> Resume signal <span>02</span></button><button onClick={() => setView('desk')} className={view==='desk'?'selected':''}><Sparkles size={17}/> Application desk <span>03</span></button><button onClick={() => setView('api')} className={view==='api'?'selected':''}><Code2 size={17}/> API studio <span>04</span></button></div><div className="side-foot"><span className="avatar">YA</span><div><strong>Yash's studio</strong><small>{usage} signal units used</small></div></div></aside>
        <section className="work-surface">{toast && <div className="toast"><Check size={15}/>{toast}<button onClick={() => setToast('')}><X size={14}/></button></div>}
          {view==='overview' && <><div className="surface-head"><div><span className="eyebrow">FIT MAP / LIVE</span><h2>Roles with a reason.</h2><p>Every score is traceable to a signal in your profile.</p></div><button className="outline" onClick={analyzeJobs} disabled={busy==='analyze'}>{busy==='analyze'?<LoaderCircle className="spin" size={16}/>:<Gauge size={16}/>} Recalculate orbit</button></div><div className="metrics"><div><strong>{jobs.length || '—'}</strong><span>roles in orbit</span></div><div><strong>{analysis.length ? `${Math.max(...analysis.map((a) => a.score))}%` : '—'}</strong><span>highest signal</span></div><div><strong>{drafts.length}</strong><span>drafts ready</span></div><div><strong>100%</strong><span>human reviewed</span></div></div><div className="job-grid">{sortedJobs.map((job) => <JobCard key={job.id} job={job} score={scoreFor(job.id)} onOpen={() => setSelected(job)} onDraft={() => createDraft(job)} busy={busy === `draft-${job.id}`}/>)}</div></>}
          {view==='signal' && <SignalPanel resumeText={resumeText} setResumeText={setResumeText} onSample={() => setResumeText(sample)} onSave={saveProfile} busy={busy==='profile'} profile={profile}/>} 
          {view==='desk' && <DeskPanel drafts={drafts} jobs={jobs} selected={selected} onSelect={setSelected}/>} 
          {view==='api' && <ApiPanel/>}
        </section></section>
      {selected && view==='overview' && <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside className="drawer" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}><X size={18}/></button><span className="eyebrow">ROLE SIGNAL / {String(scoreFor(selected.id)?.score || '—').padStart(2,'0')}</span><h2>{selected.role}</h2><p className="company">{selected.company} · {selected.location}</p><p>{selected.description}</p><div className="reason-list">{(scoreFor(selected.id)?.reasons || ['Run the fit map to reveal the evidence.']).map((r) => <div key={r}><span>+</span>{r}</div>)}</div><button className="primary full" onClick={() => createDraft(selected)} disabled={busy.startsWith('draft-')}>{busy.startsWith('draft-')?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} Draft with my signal</button></aside></div>}
    </main><footer><span>signal/arc — built for the next chapter</span><span>Resume data stays scoped to your workspace · <a href="https://github.com/YashAnand69" target="_blank" rel="noreferrer">open source minded ↗</a></span></footer>
  </div>;
}
function JobCard({job,score,onOpen,onDraft,busy}:{job:Job;score?:Analysis;onOpen:()=>void;onDraft:()=>void;busy:boolean}) { return <article className="job-card" style={{'--accent':job.accent} as React.CSSProperties} onClick={onOpen}><div className="job-top"><span className="company-dot"/ ><span>{job.company}</span><span className="job-kind">{job.kind}</span></div><h3>{job.role}</h3><p>{job.location} · {job.salary}</p><div className="tag-row">{job.tags.slice(0,3).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="job-bottom"><div className="score"><strong>{score?.score ?? '—'}</strong><span>signal</span></div><button onClick={(e) => {e.stopPropagation();onDraft();}} disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Sparkles size={15}/>} Draft</button></div></article> }
function SignalPanel({resumeText,setResumeText,onSample,onSave,busy,profile}:{resumeText:string;setResumeText:(v:string)=>void;onSample:()=>void;onSave:()=>void;busy:boolean;profile:Profile|null}) { return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">RESUME SIGNAL / ENRICH</span><h2>Give the system something real.</h2><p>Paste a resume, a profile, or the rough notes you actually use.</p></div><button className="outline" onClick={onSample}><Upload size={16}/> Load sample</button></div><div className="signal-editor"><div className="editor-top"><span><span className="window-dot red"/><span className="window-dot amber"/><span className="window-dot green"/> profile.signal</span><span>plain text → structured signal</span></div><textarea value={resumeText} onChange={(e) => setResumeText(e.target.value)} placeholder="Paste your resume or profile notes here…"/><div className="editor-bottom"><span>{resumeText.length} characters · private workspace</span><button className="primary" onClick={onSave} disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Layers3 size={16}/>} Parse my signal</button></div></div>{profile && <div className="parsed-card"><span className="eyebrow">PARSED PROFILE / READY</span><div className="parsed-main"><div><h3>{profile.full_name}</h3><p>{profile.headline}</p></div><div className="skill-cloud">{profile.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></div>}</div> }
function DeskPanel({drafts,jobs,selected,onSelect}:{drafts:Draft[];jobs:Job[];selected:Job|null;onSelect:(j:Job)=>void}) { const current=selected || jobs.find((j) => j.id===drafts[0]?.job_id); const draft=drafts.find((d) => d.job_id===current?.id); return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">APPLICATION DESK / REVIEW</span><h2>Keep your voice.</h2><p>Every draft is a starting point, never a send button.</p></div><span className="review-badge"><Check size={14}/> human review</span></div><div className="desk-layout"><div className="draft-list">{drafts.length?drafts.map((item) => { const job=jobs.find((j) => j.id===item.job_id); return <button key={item.id} className={current?.id===job?.id?'active':''} onClick={() => job&&onSelect(job)}><span>{job?.company}</span><strong>{job?.role}</strong><small>Draft · {item.status}</small></button> }):<div className="empty"><Sparkles size={22}/><p>Your first tailored draft will appear here.</p></div>}</div><div className="draft-view">{draft&&current?<><div className="draft-heading"><div><span className="eyebrow">DRAFT / {current.company.toUpperCase()}</span><h3>{current.role}</h3></div><span className="status-pill">REVIEW</span></div><textarea defaultValue={draft.body}/><div className="draft-actions"><span>Editable · never auto-sent</span><button className="primary"><Check size={16}/> Mark reviewed</button></div></>:<div className="empty large"><FileText size={28}/><p>Select a draft to review.</p></div>}</div></div></div> }
function ApiPanel() { return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">API STUDIO / ENRICH</span><h2>A small surface for big systems.</h2><p>Signal Arc exposes the same pipeline as a documented API.</p></div><span className="api-status"><span className="pulse"/> endpoint online</span></div><div className="api-grid"><div className="api-card"><div className="api-label"><span className="method post">POST</span><code>/api/profile</code></div><h3>Resume → structured signal</h3><p>Parse skills and profile context in one request. Designed for ATS and internal tool builders.</p><pre>{`fetch('/api/profile', {\n  method: 'POST',\n  body: JSON.stringify({\n    resumeText: '...'\n  })\n})`}</pre></div><div className="api-card accent-card"><BarChart3 size={24}/><h3>Metered by intent.</h3><p>{'Every parse, fit map, and draft records a usage event. The dashboard is ready for a future billing layer.'}</p><div className="api-stat"><strong>3</strong><span>pipeline primitives</span></div></div></div></div> }
