import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { api, authClient, downloadText } from './client';
import { Account, AddRole, Tracker, importResume, type Application } from './WorkspaceTools';
import { ArrowUpRight, BarChart3, Check, ChevronRight, Code2, FileText, Gauge, Github, Layers3, LoaderCircle, Radar, Sparkles, Upload, X } from 'lucide-react';
const OrbitScene = lazy(() => import('./OrbitScene').then((module) => ({ default: module.OrbitScene })));

type Job = { id: string; company: string; role: string; location: string; kind: string; salary: string; description: string; tags: string[]; accent: string; session_id?: string | null; source_url?: string };
type Profile = { session_id: string; resume_text: string; full_name: string; headline: string; skills: string[] };
type Analysis = { job_id: string; score: number; reasons: string[] };
type Draft = { id: string; job_id: string; body: string; status: string };
const sample = `Yash Anand\nProduct engineer & creative technologist\n\nI build full-stack products with React, TypeScript, Node, Python, Postgres, and Three.js. I care about design systems, API reliability, motion, observability, and turning complex workflows into clear experiences.\n\nSelected work: open-source workflow automation engine, AI review tooling, interactive 3D product sites.`;


export default function App() {
  const [profile, setProfile] = useState<Profile | null>(null); const [resumeText, setResumeText] = useState(''); const [jobs, setJobs] = useState<Job[]>([]); const [analysis, setAnalysis] = useState<Analysis[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [usage, setUsage] = useState(0); const [view, setView] = useState<'overview'|'signal'|'desk'|'api'|'tracker'>('overview'); const [selected, setSelected] = useState<Job | null>(null); const [busy, setBusy] = useState(''); const [toast, setToast] = useState('');
  const [applications,setApplications]=useState<Application[]>([]),[email,setEmail]=useState(''),[connection,setConnection]=useState<'loading'|'online'|'offline'>('loading'),[search,setSearch]=useState('');
  async function refresh(){try{const d=await api('bootstrap');setProfile(d.profile);setResumeText(d.profile?.resume_text||'');setJobs(d.jobs);setAnalysis(d.analysis);setDrafts(d.drafts);setApplications(d.applications||[]);setUsage(d.usageCount||0);setEmail(d.user?.email||'');setConnection('online');}catch(e){setConnection('offline');setToast((e as Error).message);}}
  async function signedIn(){const {data}=await(await authClient()).auth.getSession();if(data.session)await api('claim',{method:'POST',body:'{}'});setSelected(null);await refresh();}
  useEffect(() => { let mounted=true,unsubscribe:(()=>void)|undefined;authClient().then(async client=>{const {data}=await client.auth.getSession();if(!mounted)return;if(data.session)await api('claim',{method:'POST',body:'{}'});if(mounted)await refresh();const {data:listener}=client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')setTimeout(()=>{if(mounted)refresh();},0);});unsubscribe=()=>listener.subscription.unsubscribe();}).catch(()=>{if(mounted)refresh();});return()=>{mounted=false;unsubscribe?.();};}, []);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.target.classList.toggle('is-visible', entry.isIntersecting)), { threshold: 0.3 }); document.querySelectorAll('.track-item').forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, []);
  const scoreFor = (id: string) => analysis.find((item) => item.job_id === id);
  const sortedJobs = useMemo(() => [...jobs].filter(job=>`${job.company} ${job.role} ${job.location} ${job.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => (scoreFor(b.id)?.score || 0) - (scoreFor(a.id)?.score || 0)), [jobs, analysis, search]);
  const openView = (next: 'overview'|'signal'|'desk'|'api'|'tracker') => { if (next === 'overview') setSelected(null); setView(next); document.getElementById('workspace')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  async function saveProfile() { setBusy('profile'); try { const d = await api('profile', { method:'POST', body: JSON.stringify({ resumeText }) }); setProfile(d.profile); setAnalysis([]); setUsage((x) => x + 1); setToast('Profile signal updated.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function analyzeJobs() { setBusy('analyze'); try { const d = await api('analyze', { method:'POST', body:'{}' }); setAnalysis(d.analysis); setUsage((x) => x + jobs.length); setToast('Fit map recalculated across the role orbit.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function createDraft(job: Job) { setBusy(`draft-${job.id}`); try { const d = await api('drafts', { method:'POST', body: JSON.stringify({ jobId: job.id }) }); setDrafts((old) => [d.draft, ...old.filter(x=>x.id!==d.draft.id)]); setSelected(job); setView('desk'); setUsage((x) => x + 1); setToast('Draft ready for your review.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function updateDraft(id: string, body: string, status: 'review'|'reviewed') { setBusy(`draft-save-${id}`); try { const d = await api('drafts', { method:'PATCH', body: JSON.stringify({ id, body, status }) }); setDrafts((old) => old.map((item) => item.id === id ? d.draft : item)); setToast(status === 'reviewed' ? 'Draft marked reviewed.' : 'Changes saved.'); } catch(e) { setToast((e as Error).message); } finally { setBusy(''); } }
  async function saveApplication(value: Application){setBusy(`application-${value.job_id}`);try{const d=await api('applications',{method:'POST',body:JSON.stringify(value)});setApplications(old=>[d.application,...old.filter(a=>a.job_id!==value.job_id)]);setToast('Application progress saved.');}catch(e){setToast((e as Error).message);}finally{setBusy('');}}
  async function removeApplication(id:string){setBusy(`application-${id}`);try{await api('applications',{method:'DELETE',body:JSON.stringify({job_id:id})});setApplications(old=>old.filter(a=>a.job_id!==id));}catch(e){setToast((e as Error).message);}finally{setBusy('');}}
  return <div className="app-shell">
    <div className="ambient-signal" aria-hidden="true"><Suspense fallback={null}><OrbitScene mode={view} hasProfile={Boolean(profile)} /></Suspense></div>
    <header className="topbar"><a href="#top" className="wordmark"><span className="mark">◎</span> signal<span className="slash">/</span>arc</a><nav><button onClick={() => openView('overview')} className={view==='overview'?'active':''}>Workspace</button><button onClick={() => openView('signal')} className={view==='signal'?'active':''}>Resume signal</button><button onClick={() => openView('api')} className={view==='api'?'active':''}>API studio</button></nav><Account email={email} onSignedIn={signedIn} onError={setToast}/><a className="github" href="https://github.com/YashAnand69/signal-arc" target="_blank" rel="noreferrer"><Github size={16}/> Build log <ArrowUpRight size={14}/></a></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><div className="hero-intro"><div className="eyebrow"><span className="pulse"/> A NEW PERSPECTIVE / CAREER INTELLIGENCE</div><h1>Find your<br/>next <i>dimension.</i></h1><p className="lede">Turn your experience into a clearer path forward. Decode your strengths, see why a role fits, and write an application that still sounds like you.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById('workspace')?.scrollIntoView({ behavior:'smooth' })}>Explore your fit <ArrowUpRight size={17}/></button><span className="micro">SCROLL / DISCOVER → EXPAND → ALIGN</span></div><div className="hero-proof"><span className="proof-spark">✳</span><span>From scattered experience<br/>to a sharper next move.</span><span className="proof-line"/></div></div><div className="hero-track"><div className="track-item"><span>01 / DISCOVER</span><strong>Start with what<br/>you’ve built.</strong><p>Your resume becomes a readable set of strengths and skills.</p></div><div className="track-item"><span>02 / EXPAND</span><strong>Find the roles<br/>that make sense.</strong><p>Fit scores show their working, so you can decide for yourself.</p></div><div className="track-item"><span>03 / ALIGN</span><strong>Tell the right<br/>story, your way.</strong><p>Use an editable draft as a starting point for every application.</p></div></div></div><div className="hero-index">SIGNAL ARC © 2026 <span>SCROLL TO EXPLORE ↓</span></div></section>
      <section className="ticker"><span>PARSE</span><b>→</b><span>COMPARE</span><b>→</b><span>EXPLAIN</span><b>→</b><span>REVIEW</span><b>→</b><span>APPLY WITH INTENT</span></section>
      <section id="workspace" className="workspace"><aside className="sidebar"><div className="side-top"><span className="eyebrow">YOUR SIGNAL / 01</span><span className="live-dot">LIVE</span></div><h2>One clear<br/><i>next step.</i></h2><p>Build a small, honest system for the work you want.</p><div className="side-nav"><button onClick={() => { setSelected(null); setView('overview'); }} className={view==='overview'?'selected':''}><Radar size={17}/> Fit map <span>01</span></button><button onClick={() => setView('signal')} className={view==='signal'?'selected':''}><FileText size={17}/> Resume signal <span>02</span></button><button onClick={() => setView('desk')} className={view==='desk'?'selected':''}><Sparkles size={17}/> Application desk <span>03</span></button><button onClick={() => setView('api')} className={view==='api'?'selected':''}><Code2 size={17}/> API studio <span>04</span></button></div><button className={`tracker-nav ${view==='tracker'?'selected':''}`} onClick={()=>setView('tracker')}><Layers3 size={17}/> Application tracker <span>{applications.length}</span></button><button className="text-button export-workspace" onClick={async()=>{try{const d=await api('export');downloadText('signal-arc-workspace.json',JSON.stringify(d,null,2),'application/json');}catch(e){setToast((e as Error).message);}}}>Export my workspace</button><button className="text-button clear-workspace" onClick={async()=>{if(!window.confirm('Clear your saved resume, private roles, drafts, and application history? Export a backup first. This cannot be undone.'))return;try{await api('workspace',{method:'DELETE',body:'{}'});setSelected(null);setView('overview');await refresh();setToast('Workspace cleared.');}catch(e){setToast((e as Error).message);}}}>Clear workspace data</button><div className="side-foot"><span className="avatar">YA</span><div><strong>{email?email.split('@')[0]:profile?.full_name||'Your studio'}</strong><small>{usage} signal units used</small></div></div></aside>
        <section className="work-surface"><div className={`connection-note ${connection}`} role="status">{connection==='loading'?'Connecting to your workspace…':connection==='online'?(email?'Account workspace · saved across devices':'Guest workspace · saved in this browser. Sign in to sync.'):<><span>Workspace offline. Changes cannot be saved.</span><button className="text-button" onClick={refresh}>Retry connection</button></>}</div>{toast && <div className="toast" role="status"><Check size={15}/>{toast}<button onClick={() => setToast('')}><X size={14}/></button></div>}
          {view==='overview' && <><div className="surface-head"><div><span className="eyebrow">FIT MAP / YOUR ROLES</span><h2>Roles with a reason.</h2><p>Compare your own opportunities. The four starting roles are labeled examples.</p></div><div className="surface-actions"><AddRole onAdded={job=>{setJobs(old=>[job,...old]);setAnalysis([]);setToast('Private role added. Recalculate to compare it.');}} onError={setToast}/><button className="outline" onClick={profile ? analyzeJobs : () => openView('signal')} disabled={busy==='analyze'}>{busy==='analyze'?<LoaderCircle className="spin" size={16}/>:<Gauge size={16}/>} {profile ? 'Recalculate orbit' : 'Add your signal'}</button></div></div><label className="role-search">Search roles<input type="search" placeholder="Role, company, location, or skill…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="metrics"><div><strong>{jobs.length || '—'}</strong><span>roles in orbit</span></div><div><strong>{analysis.length ? `${Math.max(...analysis.map((a) => a.score))}%` : '—'}</strong><span>highest signal</span></div><div><strong>{drafts.length}</strong><span>drafts ready</span></div><div><strong>{drafts.filter((item) => item.status === 'reviewed').length}</strong><span>reviewed by you</span></div></div><div className="job-grid">{!sortedJobs.length&&<div className="empty"><p>{connection==='loading'?'Loading your roles…':'No roles match. Add a role or clear your search.'}</p></div>}{sortedJobs.map((job) => <JobCard key={job.id} job={job} score={scoreFor(job.id)} onOpen={() => setSelected(job)} onDraft={() => profile ? createDraft(job) : openView('signal')} busy={busy === `draft-${job.id}`}/>)}</div></>}
          {view==='signal' && <SignalPanel resumeText={resumeText} setResumeText={setResumeText} onSample={() => setResumeText(sample)} onSave={saveProfile} busy={busy==='profile'} profile={profile}/>}
          {view==='desk' && <DeskPanel drafts={drafts} jobs={jobs} selected={selected} onSelect={setSelected} onSave={updateDraft} busy={busy}/>}
          {view==='tracker' && <Tracker jobs={jobs} applications={applications} onSave={saveApplication} onRemove={removeApplication} busy={busy}/>}
          {view==='api' && <ApiPanel connection={connection}/>}
        </section></section>
      {selected && view==='overview' && <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside className="drawer" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}><X size={18}/></button><span className="eyebrow">ROLE SIGNAL / {String(scoreFor(selected.id)?.score || '—').padStart(2,'0')}</span><h2>{selected.role}</h2><p className="company">{selected.company} · {selected.location}</p><p>{selected.description}</p>{selected.source_url&&<a className="listing-link" href={selected.source_url} target="_blank" rel="noreferrer">View original listing ↗</a>}<button className="outline full" disabled={busy===`application-${selected.id}`} onClick={async()=>{if(!applications.some(a=>a.job_id===selected.id))await saveApplication({job_id:selected.id,stage:'saved',notes:'',deadline:null,updated_at:new Date().toISOString()});setSelected(null);setView('tracker');}}>{applications.some(a=>a.job_id===selected.id)?'View application progress':'Track application'}</button>{selected.session_id&&<button className="text-button" onClick={async()=>{if(!window.confirm('Remove this private role and its drafts, scores, and tracking history?'))return;try{await api('roles',{method:'DELETE',body:JSON.stringify({id:selected.id})});setSelected(null);await refresh();setToast('Role removed.');}catch(e){setToast((e as Error).message);}}}>Remove this role</button>}<div className="reason-list">{(scoreFor(selected.id)?.reasons || ['Run the fit map to reveal the evidence.']).map((r) => <div key={r}><span>+</span>{r}</div>)}</div><button className="primary full" onClick={() => profile ? createDraft(selected) : openView('signal')} disabled={busy.startsWith('draft-')}>{busy.startsWith('draft-')?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {profile ? 'Draft with my signal' : 'Add signal to draft'}</button></aside></div>}
    </main><footer><span>signal/arc — built for the next chapter</span><span>Resume data stays scoped to your workspace · <a href="https://github.com/YashAnand69/signal-arc" target="_blank" rel="noreferrer">view the source ↗</a></span></footer>
  </div>;
}
function JobCard({job,score,onOpen,onDraft,busy}:{job:Job;score?:Analysis;onOpen:()=>void;onDraft:()=>void;busy:boolean}) { return <article className="job-card" style={{'--accent':job.accent} as React.CSSProperties} onClick={onOpen} onKeyDown={(event) => { if (event.target === event.currentTarget && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); onOpen(); } }} tabIndex={0} role="button" aria-label={`View ${job.role} at ${job.company}`}><div className="job-top"><span className="company-dot"/ ><span>{job.company}</span><span className="job-kind">{job.session_id?'YOUR ROLE':'SAMPLE'}</span></div><h3>{job.role}</h3><p>{job.location} · {job.salary}</p><div className="tag-row">{job.tags.slice(0,3).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="job-bottom"><div className="score"><strong>{score?.score ?? '—'}</strong><span>skill coverage</span></div><button onClick={(e) => {e.stopPropagation();onDraft();}} disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:<Sparkles size={15}/>} Draft</button></div></article> }
function SignalPanel({resumeText,setResumeText,onSample,onSave,busy,profile}:{resumeText:string;setResumeText:(v:string)=>void;onSample:()=>void;onSave:()=>void;busy:boolean;profile:Profile|null}) { const [importing,setImporting]=useState(false),[importError,setImportError]=useState(''); return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">RESUME SIGNAL / ENRICH</span><h2>Give the system something real.</h2><p>Paste a resume, a profile, or the rough notes you actually use.</p></div><div className="surface-actions"><label className="outline upload-label"><Upload size={16}/>{importing?'Reading…':'Import resume'}<input type="file" accept=".pdf,.docx,.txt,.md" disabled={importing} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setImporting(true);setImportError('');try{setResumeText(await importResume(file));}catch(error){setImportError((error as Error).message);}finally{setImporting(false);e.target.value='';}}}/></label><button className="outline" onClick={onSample}>Load sample</button></div></div>{importError&&<p role="alert" className="form-error">{importError}</p>}<p className="import-note">PDF, DOCX, TXT · up to 8 MB. Files are read in your browser; only the text you save reaches your workspace. Put your name and headline on the first two lines.</p><div className="signal-editor"><div className="editor-top"><span><span className="window-dot red"/><span className="window-dot amber"/><span className="window-dot green"/> profile.signal</span><span>plain text → structured signal</span></div><textarea aria-label="Resume text" maxLength={100000} value={resumeText} onChange={(e) => setResumeText(e.target.value)} placeholder="Paste your resume or profile notes here…"/><div className="editor-bottom"><span>{resumeText.trim().length < 20 ? 'Add at least 20 characters to begin' : `${resumeText.length} characters · private workspace`}</span><button className="primary" onClick={onSave} disabled={busy || resumeText.trim().length < 20}>{busy?<LoaderCircle className="spin" size={16}/>:<Layers3 size={16}/>} Parse my signal</button></div></div>{profile && <div className="parsed-card"><span className="eyebrow">PARSED PROFILE / READY</span><div className="parsed-main"><div><h3>{profile.full_name}</h3><p>{profile.headline}</p></div><div className="skill-cloud">{profile.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></div>}</div> }
function DeskPanel({drafts,jobs,selected,onSelect,onSave,busy}:{drafts:Draft[];jobs:Job[];selected:Job|null;onSelect:(j:Job)=>void;onSave:(id:string,body:string,status:'review'|'reviewed')=>Promise<void>;busy:string}) {
  const [activeId,setActiveId]=useState<string|null>(null);
  const current = jobs.find(job=>job.id===drafts.find(d=>d.id===activeId)?.job_id) || selected || jobs.find((job) => job.id === drafts[0]?.job_id);
  const draft = drafts.find(item=>item.id===activeId) || drafts.find((item) => item.job_id === current?.id);
  const [body, setBody] = useState('');
  const [copied, setCopied] = useState(false);
  useEffect(() => { setBody(draft?.body || ''); setCopied(false); }, [draft?.id, draft?.body]);
  const saving = busy === `draft-save-${draft?.id}`;
  return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">APPLICATION DESK / REVIEW</span><h2>Keep your voice.</h2><p>Edit every line until it sounds like you. Nothing is sent for you.</p></div><span className="review-badge"><Check size={14}/> human review</span></div><div className="desk-layout"><div className="draft-list">{drafts.length ? drafts.map((item) => { const job=jobs.find((candidate) => candidate.id===item.job_id); return <button key={item.id} className={draft?.id===item.id?'active':''} onClick={() => {setActiveId(item.id);if(job)onSelect(job);}}><span>{job?.company}</span><strong>{job?.role}</strong><small>Draft · {item.status}</small></button> }) : <div className="empty"><Sparkles size={22}/><p>Your first tailored draft will appear here.</p></div>}</div><div className="draft-view">{draft&&current ? <><div className="draft-heading"><div><span className="eyebrow">DRAFT / {current.company.toUpperCase()}</span><h3>{current.role}</h3></div><span className="status-pill">{draft.status.toUpperCase()}</span></div><textarea aria-label="Edit application draft" value={body} onChange={(event) => setBody(event.target.value)}/><div className="draft-actions"><span>{body === draft.body ? 'All changes saved' : 'Unsaved changes'}</span><div className="draft-action-buttons"><button className="outline" onClick={()=>downloadText('application-draft.txt',body)}>Download</button><button className="outline" onClick={async () => { try{await navigator.clipboard.writeText(body);setCopied(true);}catch{setCopied(false);window.alert('Copy is unavailable in this browser. Use Download instead.');} }}>{copied ? 'Copied' : 'Copy text'}</button><button className="outline" disabled={saving || body === draft.body || body.trim().length < 20} onClick={() => onSave(draft.id,body,'review')}>Save changes</button><button className="primary" disabled={saving || draft.status === 'reviewed' || body.trim().length < 20} onClick={() => onSave(draft.id,body,'reviewed')}>{saving ? <LoaderCircle className="spin" size={16}/> : <Check size={16}/>} {draft.status === 'reviewed' ? 'Reviewed' : 'Mark reviewed'}</button></div></div></> : <div className="empty large"><FileText size={28}/><p>Select a draft to review.</p></div>}</div></div></div>;
}
function ApiPanel({connection}:{connection:string}) { return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">API STUDIO / ENRICH</span><h2>A small surface for big systems.</h2><p>Signal Arc exposes the same pipeline as a documented API.</p></div><span className="api-status"><span className="pulse"/> {connection==='online'?'database connected':'connection unavailable'}</span></div><div className="api-grid"><div className="api-card"><div className="api-label"><span className="method post">POST</span><code>/api/profile</code></div><h3>Resume → structured signal</h3><p>Parse skills and profile context in one request. Designed for ATS and internal tool builders.</p><pre>{`fetch('/api/profile', {\n  method: 'POST',\n  body: JSON.stringify({\n    resumeText: '...'\n  })\n})`}</pre></div><div className="api-card accent-card"><BarChart3 size={24}/><h3>Metered by intent.</h3><p>{'Every parse, fit map, and draft records a usage event. The dashboard is ready for a future billing layer.'}</p><div className="api-stat"><strong>3</strong><span>pipeline primitives</span></div></div></div></div> }
