import { useState } from 'react';
import { Plus, Bookmark, Download, LogIn, X, LoaderCircle } from 'lucide-react';
import { api, authClient, downloadText } from './client';
export type Application = {job_id:string;stage:string;notes:string;deadline:string|null;updated_at:string};
type Role={id:string;company:string;role:string;source_url?:string};
export function Account({email,onSignedIn,onError}:{email?:string;onSignedIn:()=>Promise<void>;onError:(message:string)=>void}) {
 const [open,setOpen]=useState(false),[address,setAddress]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 return <><button className="outline account-button" onClick={()=>setOpen(true)}><LogIn size={15}/>{email?'Account':'Sign in'}</button>{open&&<div className="drawer-backdrop" onClick={()=>setOpen(false)}><section className="account-dialog" role="dialog" aria-modal="true" aria-label="Your account" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close account" onClick={()=>setOpen(false)}><X size={18}/></button><span className="eyebrow">YOUR WORKSPACE / SYNC</span><h2>{email?'Your account':'Keep your next move.'}</h2>{email?<><p>Signed in as {email}. Your workspace is available across devices.</p><button className="outline" disabled={busy} onClick={()=>run(async()=>{await (await authClient()).auth.signOut();await onSignedIn();setOpen(false);})}>Sign out</button></>:<><p>Sign in to sync your roles, resume, drafts, and application history. Guest work is carried into your account.</p><button className="outline full" disabled={busy} onClick={()=>run(async()=>{const {error}=await (await authClient()).auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/'}});if(error)throw error;})}>Continue with Google</button><form onSubmit={e=>{e.preventDefault();run(async()=>{const auth=(await authClient()).auth;const {error}=await auth.signInWithOtp({email:address,options:{emailRedirectTo:window.location.origin+'/'}});if(error)throw error;setSent(true);});}}><label>Email<input type="email" required value={address} disabled={sent} onChange={e=>setAddress(e.target.value)} autoComplete="email"/></label>{sent&&<p role="status">Check your email and open the sign-in link in this browser. Keep this tab until you sign in.</p>}<button className="primary full" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:null}{sent?'Resend sign-in link':'Send sign-in link'}</button>{sent&&<button className="text-button" type="button" onClick={()=>{setSent(false);}}>Use another email</button>}</form><small>Google is recommended. Email delivery depends on the configured email provider.</small></>}</section></div>}</>;
}
export function AddRole({onAdded,onError}:{onAdded:(job:any)=>void;onError:(text:string)=>void}) {
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[values,setValues]=useState({company:'',role:'',description:'',location:'',salary:'',source_url:'',tags:''});
 return <><button className="outline" onClick={()=>setOpen(true)}><Plus size={16}/> Add a role</button>{open&&<div className="drawer-backdrop" onClick={()=>setOpen(false)}><section className="account-dialog role-dialog" role="dialog" aria-modal="true" aria-label="Add a role" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close role form" onClick={()=>setOpen(false)}><X size={18}/></button><span className="eyebrow">REAL ROLES / YOUR SEARCH</span><h2>Add your next opportunity.</h2><p>Paste the description from a real listing. Only your workspace can see it.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const d=await api('ingest',{method:'POST',body:JSON.stringify({...values,tags:values.tags.split(',').map(x=>x.trim()).filter(Boolean)})});onAdded(d.job);setOpen(false);setValues({company:'',role:'',description:'',location:'',salary:'',source_url:'',tags:''});}catch(error){onError((error as Error).message);}finally{setBusy(false);}}}>{(['company','role','location','salary','source_url','tags'] as const).map(field=><label key={field}>{({company:'Company',role:'Role title',location:'Location (optional)',salary:'Salary (optional)',source_url:'Original HTTPS listing (optional)',tags:'Additional skills, separated by commas (optional)'})[field]}<input type={field==='source_url'?'url':'text'} required={field==='company'||field==='role'} maxLength={field==='source_url'?2000:200} value={values[field]} onChange={e=>setValues({...values,[field]:e.target.value})}/></label>)}<label>Job description<textarea required minLength={20} maxLength={20000} value={values.description} onChange={e=>setValues({...values,description:e.target.value})}/></label><button className="primary full" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Plus size={16}/>}Save role</button></form></section></div>}</>;
}
export function Tracker({jobs,applications,onSave,onRemove,busy}:{jobs:Role[];applications:Application[];onSave:(value:Application)=>Promise<void>;onRemove:(id:string)=>Promise<void>;busy:string}) {
 const stages=['saved','applied','interview','offer','closed'];
 return <div className="panel-stack"><div className="surface-head"><div><span className="eyebrow">APPLICATIONS / YOUR PROGRESS</span><h2>A search with direction.</h2><p>Track the real steps you take. Stage changes never submit an application.</p></div><button className="outline" onClick={()=>downloadText('signal-arc-applications.csv',['Company,Role,Stage,Deadline,Notes',...applications.map(a=>{const j=jobs.find(x=>x.id===a.job_id);return[j?.company,j?.role,a.stage,a.deadline,a.notes].map(v=>'"'+String(v||'').replace(/"/g,'""')+'"').join(',');})].join('\n'),'text/csv')}><Download size={16}/>Export CSV</button></div><div className="stage-summary">{stages.map(stage=><div key={stage}><strong>{applications.filter(a=>a.stage===stage).length}</strong><span>{stage}</span></div>)}</div>{applications.length?<div className="tracking-list">{applications.map(a=><TrackingItem key={a.job_id} value={a} job={jobs.find(j=>j.id===a.job_id)} onSave={onSave} onRemove={onRemove} busy={busy===`application-${a.job_id}`}/>)}</div>:<div className="empty large"><Bookmark size={28}/><p>Open a role and choose “Track application” to start your search history.</p></div>}</div>;
}
function TrackingItem({value,job,onSave,onRemove,busy}:{value:Application;job?:Role;onSave:(value:Application)=>Promise<void>;onRemove:(id:string)=>Promise<void>;busy:boolean}) {
 const [stage,setStage]=useState(value.stage),[notes,setNotes]=useState(value.notes),[deadline,setDeadline]=useState(value.deadline||'');const dirty=stage!==value.stage||notes!==value.notes||deadline!==(value.deadline||'');
 return <article className="tracking-item"><div><span className="eyebrow">{job?.company}</span><h3>{job?.role}</h3>{job?.source_url&&<a href={job.source_url} target="_blank" rel="noreferrer">View original listing ↗</a>}</div><div className="tracking-fields"><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}>{['saved','applied','interview','offer','closed'].map(s=><option key={s}>{s}</option>)}</select></label><label>Deadline<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label className="tracking-notes">Private notes<textarea maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Next steps, interview notes, contact details…"/></label></div><div className="tracking-actions"><small>{dirty?'Unsaved changes':`Saved ${new Date(value.updated_at).toLocaleDateString()}`}</small><button className="outline" disabled={busy} onClick={()=>onRemove(value.job_id)}>Untrack</button><button className="primary" disabled={busy||!dirty} onClick={()=>onSave({...value,stage,notes,deadline:deadline||null})}>{busy?'Saving…':'Save progress'}</button></div></article>;
}
export async function importResume(file: File) {
 if(file.size>8*1024*1024)throw new Error('Use a resume smaller than 8 MB.');const extension=file.name.split('.').pop()?.toLowerCase();
 if(extension==='txt'||extension==='md')return file.text();
 if(extension==='docx'){const mammoth=await import('mammoth');const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return result.value;}
 if(extension==='pdf'){const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).href;const doc=await pdf.getDocument({data:await file.arrayBuffer()}).promise;try{if(doc.numPages>30)throw new Error('Use a resume with at most 30 pages.');const pages=[];for(let i=1;i<=doc.numPages;i++){const text=await(await doc.getPage(i)).getTextContent();pages.push(text.items.map(item=>'str'in item?item.str+('hasEOL'in item&&item.hasEOL?'\n':' '):'').join(''));}const result=pages.join('\n');if(result.trim().length<20)throw new Error('This PDF contains no readable text. Paste the text from your resume instead.');return result;}finally{await doc.destroy();}}
 throw new Error('Choose a PDF, DOCX, TXT, or Markdown file.');
}
